# Generated by Django 5.1.3 on 2024-11-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
    ]
