# Generated by Django 5.1.3 on 2024-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=24, default=None,),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine',
            field=models.CharField(max_length=24),
        ),
    ]
